#!/usr/bin/env python3
# %% [markdown]
# # Labeler for Examples
# This is the program to perform labeling examples for supervised learning for
# the anomality detection of Airconditioner.
#
# *Author*: Steven Yuan
#
# *Project lead*: Yu Shen
#
# ## Import packages

# %%
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_theme()

from IPython.display import clear_output
from tqdm import tqdm

from importlib import reload

# %% [markdown]
# aclabeler is a package that contains the functions to label the data.
# It defines a class called `ACLabeler` that contains the functions to label the data.
#
# %%
import sys
sys.path.insert(0, '../notebooks')

import aclabeler

# %% [markdown]
# ## Configurations
# %%
data_dir = '../../data/'  # The root directory for the data. All the paths are relative to this directory.
temps_file = 'temps/temps_indoor_15T'  # File containing the temperature data
windows_file = 'timewindows/timewindows_4H_rs2022'  # File containing the definitions of the time windows of data to be labeled
labeled_windows_file = 'timewindows/test'  # File to output the labels for the time windows defined in windows_file

autosave_freq = 5  # Number of labels before automatically saving
savefig_path = 'images/abnormal/'  # Path to save images generated by the labeling program

# %% [markdown]
# ## Create object labeler
#
# %%
reload(aclabeler)
from aclabeler import ACLabeler

labeler = ACLabeler(
        path=data_dir,
        windows=windows_file,
        labeled=labeled_windows_file,
        temps=temps_file
    )

# %% [markdown]
# ## Pererom labeling by launching the interactive labeling program
# %%
context_before_hrs = 4  # Number of hours to plot before current time window as context
context_after_hrs = 4  # Number of hours to plot before current time window as context
lab = labeler.label(autosave_freq=autosave_freq,
                    context_before_hrs=context_before_hrs,
                    context_after_hrs=context_after_hrs,
                    savefig_path=savefig_path,
                    show_score=False
                   )


# %%
